WorkingWithMultipleTable_Prod/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using WorkingWithMultipleTable_Prod.Data;

using WorkingWithMultipleTable_Prod.Models;
using WorkingWithMultipleTable_Prod.Utility;

namespace WorkingWithMultipleTable_Prod.Controllers
{
    [Authorize]
    public class CustomerController : Controller
    {
        private readonly ApplicationContext _context;
        

        public CustomerController(ApplicationContext context)
        {
            _context = context;
          
            
        }

        
         
        public IActionResult Index()
        {
            var data = _context.Customers.ToList();
            return View(data);
        }

        public IActionResult UploadFile()
        {
            return View();
        }
        [HttpPost]
        public IActionResult UploadFile(IFormFile file)
        {
            List<Customer> cust = new();
            try
            {
                if (file != null && file.Length > 0)
                {
                    using(var pkg = new ExcelPackage(file.OpenReadStream()))
                    {
                        ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
                        var worksheet = pkg.Workbook.Worksheets[0];
                        for ( int row = 2; row<=worksheet.Dimension.End.Row; row++)
                        {
                            cust.Add(new Customer
                            {
                                CustomerId = worksheet.Cells[row, 1].Text,
                                FirstName = worksheet.Cells[row, 2].Text,
                                LastName = worksheet.Cells[row, 3].Text,
                                Country = worksheet.Cells[row, 4].Text,
                                Gender = worksheet.Cells[row, 5].Text,
                                Email = worksheet.Cells[row, 6].Text,
                                Age = Int32.Parse(worksheet.Cells[row, 7].Text)
                           
                            });
                        }
                    }
                }
                else
                {
                    return View(file);
                }
            }
            catch (Exception)
            {

                throw;
            }
            
            return View("DisplayExcel", cust);
        }

        public IActionResult DisplayExcel()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ImportExcel(List<Customer> customers)
        {
            var data =  customers.Where(c=>c.Active).ToList();
           
                if (data != null)
                {
                    foreach (var item in data)
                    {
                    item.CustomerId = Helper.encryptText(item.CustomerId);
                        await _context.Customers.AddAsync(item);
                    }
                   await _context.SaveChangesAsync();
                }
                else
                {
                    BadRequest();
                }
           
            return RedirectToAction("Index");
        }
    }
}

WorkingWithMultipleTable_Prod/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text;
using WorkingWithMultipleTable_Prod.Data;
using WorkingWithMultipleTable_Prod.Models;
using WorkingWithMultipleTable_Prod.Models.Combined;
using WorkingWithMultipleTable_Prod.Models.ViewModel;
using WorkingWithMultipleTable_Prod.Utility;

namespace WorkingWithMultipleTable_Prod.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly ApplicationContext _context;


        public EmployeeController(ApplicationContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            //var data = _context.Employees.OrderBy(e=>e.EmployeeId).ToList();
            //CombinedViewModel emp = new CombinedViewModel();
            //emp.Employees = _context.Employees.ToList();
            //emp.Departments = _context.Departments.ToList();
            //return View(emp) ;

            var data = from e in _context.Employees
                       join d in _context.Departments
                       on e.DepartmentId equals d.DepartmentId
                       orderby e.EmployeeId
                       select new EmployeeDepartmentModel
                       {
                           EmployeeId = e.EmployeeId,
                           FirstName = Utilities.EveryStringFirstCapital(e.FirstName),
                           LastName = Utilities.EveryStringFirstCapital(e.LastName),
                           MiddleName = Utilities.EveryStringFirstCapital(e.MiddleName),
                           Gender = Utilities.EveryStringFirstCapital(e.Gender),
                           DepartmentCode = d.DepartmentCode.ToUpper(),
                           DepartmentName = Utilities.EveryStringFirstCapital(d.DepartmentName)
                       };
            return View(data);
        }
        public async Task<IActionResult> Create()
        {
            ViewData["Department"] = await _context.Departments.ToListAsync();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(EmployeeDepartmentModel employee)
        {
            ViewData["Department"] = await _context.Departments.ToListAsync();
            ModelState.Remove("DepartmentName");
            ModelState.Remove("DepartmentCode");


            if (ModelState.IsValid)
            {
                try
                {
                    if (employee.EmployeeId != 0)
                    {
                        //var emp = await _context.Employees.FindAsync(employee.EmployeeId);
                        //if (emp != null)
                        //{

                            //emp.EmployeeId = employee.EmployeeId;
                            //emp.FirstName = employee.FirstName;
                            //emp.LastName = employee.LastName;
                            //emp.MiddleName = employee.MiddleName;
                            //emp.Gender = employee.Gender;
                            //emp.DepartmentId = employee.DepartmentId;
                            var emp = new Employee()
                            {
                                EmployeeId = employee.EmployeeId,
                                FirstName = employee.FirstName,
                                LastName = employee.LastName,
                                MiddleName = employee.MiddleName,
                                Gender = employee.Gender,
                                DepartmentId = employee.DepartmentId,
                            };

                            _context.Employees.Update(emp);

                            TempData["success"] = "Record updated successfully";

                        //}
                        //else
                        //{
                        //    return NotFound();
                        //}


                    }
                    else
                    {
                        var data = new Employee()
                        {
                            FirstName = employee.FirstName,
                            LastName = employee.LastName,
                            MiddleName = employee.MiddleName,
                            Gender = employee.Gender,
                            DepartmentId = employee.DepartmentId,
                        };
                        await _context.Employees.AddAsync(data);

                        TempData["success"] = "Record saved successfully";

                    }
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {

                    TempData["Error"] = "Failed to perform operation.\n" + ex.Message;
                    return View(employee);
                }

            }
            else
            {

                return BadRequest(); 
            }


        }

        public async Task<IActionResult> Delete(int[] id)
        {
            string result = string.Empty;
            try
            {
                if (id.Length == 0)
                {
                    TempData["error"] = "No Records to Delete";
                    result = "success";
                }
                else
                {
                    foreach (var item in id)
                    {
                        if (item == 0)
                        {
                            return BadRequest();
                        }
                        else
                        {
                            var data = await _context.Employees.FindAsync(item);
                            if (data == null)
                            {
                                NotFound();
                            }
                            else
                            {
                                _context.Employees.Remove(data);

                            }
                        }
                    }
                    await _context.SaveChangesAsync();
                    TempData["success"] = "Record(s) Deleted Successfully";
                    result = "success";
                }
            }
            catch (Exception)
            {

                throw;
            }
                       
            return new JsonResult(result);

        }
        public async Task<IActionResult> Edit(int id)
        {
            EmployeeDepartmentModel employeeDepartment = new();
            ViewData["Department"] = _context.Departments.ToList();
            employeeDepartment = await (from e in _context.Employees
                       join d in _context.Departments
                       on e.DepartmentId equals d.DepartmentId
                       where e.EmployeeId == id
                       select new EmployeeDepartmentModel
                       {
                           EmployeeId = e.EmployeeId,
                           FirstName = e.FirstName,
                           LastName = e.LastName,
                           MiddleName = e.MiddleName,
                           Gender = e.Gender,
                           DepartmentId = d.DepartmentId,
                           DepartmentCode = d.DepartmentCode,
                           DepartmentName = d.DepartmentName
                       }).FirstOrDefaultAsync();
            return View("Create", employeeDepartment);
        }

        public async Task<IActionResult> Details(int id)
        {
            EmployeeDepartmentModel employeeDepartment = new EmployeeDepartmentModel();
            try
            {
                if (id == 0)
                {
                    BadRequest();
                }
                else
                {
                    employeeDepartment = await (from e in _context.Employees.Where(e => e.EmployeeId == id)
                               join d in _context.Departments
                               on e.DepartmentId equals d.DepartmentId
                               select new EmployeeDepartmentModel
                               {
                                   EmployeeId = e.EmployeeId,
                                   DepartmentId = d.DepartmentId,
                                   FirstName = Utilities.EveryStringFirstCapital(e.FirstName),
                                   LastName = Utilities.EveryStringFirstCapital(e.LastName),
                                   MiddleName = Utilities.EveryStringFirstCapital(e.MiddleName),
                                   Gender = Utilities.EveryStringFirstCapital(e.Gender),
                                   DepartmentCode = d.DepartmentCode.ToUpper(),
                                   DepartmentName = Utilities.EveryStringFirstCapital(d.DepartmentName)
                               }).FirstOrDefaultAsync();

                    if(employeeDepartment == null)
                    {
                        NotFound();
                    }
                }
            }
            catch (Exception)
            {

                throw;
            }
            return View(employeeDepartment);
        }
    }
}

WorkingWithMultipleTable_Prod/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WorkingWithMultipleTable_Prod</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/fontawesome/css/all.min.css" rel="stylesheet" />
    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WorkingWithMultipleTable_Prod.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WorkingWithMultipleTable_Prod</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="UploadFile">Upload Excel</a>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginView" />
            </div>
        </nav>
    </header>
    <div >
    <partial name="_LoaderPartial" />
    <partial name="_Notification" />
    </div>
    
        
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2024 - WorkingWithMultipleTable_Prod - <b>@DateTime.Now</b>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WorkingWithMultipleTable_Prod/Views/Shared/_LayoutDashboard.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WorkingWithMultipleTable_Prod</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/fontawesome/css/all.min.css" rel="stylesheet" />
    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WorkingWithMultipleTable_Prod.styles.css" asp-append-version="true" />
</head>
<body>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WorkingWithMultipleTable_Prod - <b>@DateTime.Now</b>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/fontawesome/js/all.min.js"></script>
    <script src="~/lib/fontawesome/js/all.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WorkingWithMultipleTable_Prod/Views/Shared/_LayoutLR.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WorkingWithMultipleTable_Prod</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/fontawesome/css/all.min.css" rel="stylesheet" />
    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WorkingWithMultipleTable_Prod.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WorkingWithMultipleTable_Prod</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <partial name="_LoginView" />
            </div>
        </nav>
    </header>
    <div>
        <partial name="_LoaderPartial" />
        <partial name="_Notification" />
        <br />
    </div>

    <div class="container">
        <div class="row">
            <div class="col-6 offset-3">
                <div class="card login-logout-card border-0">

                    <div class="card-body">
                        <div class="row justify-content-center border border-2">
                        @RenderBody()
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>


    <footer class="border-top footer text-muted text-center" style="position: relative; bottom:0">
        <div class="container">
            &copy; 2024 - WorkingWithMultipleTable_Prod - <b>@DateTime.Now</b>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
                            @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WorkingWithMultipleTable_Prod/Views/Shared/_LoaderPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div id="Loader" class="shader">

    <div class="custom_loader"></div>
</div>

<script>
    
</script>

WorkingWithMultipleTable_Prod/Views/Shared/_LoginView.cshtml
@using Microsoft.AspNetCore.Identity
@using WorkingWithMultipleTable_Prod.Models.IdentityModel;
@inject SignInManager<ApplicationUser> signinManager
@inject UserManager<ApplicationUser> userManager

<div>

    @if (signinManager.IsSignedIn(User))
    {
        
    <ul class="nav navbar">
        <li class="nav-item">
            <a class="text-muted text-dark">Welcome, @userManager.GetUserName(User)</a>
        </li>
        <li class="nav-item">
                <a asp-controller="Account" asp-action="Logout" class="nav-link text-danger"><i class="fa-solid fa-right-from-bracket"></i> Logout</a>
        </li>
    </ul>

    }
    else
    {
    <ul class="nav navbar">
        <li class="nav-item">
            <a asp-controller="Account" asp-action="Login" class="nav-link">Login</a>
        </li>
        <li class="nav-item">
            <a asp-controller="Account" asp-action="Register" class="nav-link">Register</a>
        </li>
    </ul>
    }
</div>

WorkingWithMultipleTable_Prod/Views/Shared/_Notification.cshtml
@if(TempData["success"] !=null)
{
    <div class="container" style="width: auto; float: right">
        <div class="alert alert-success notification">
            <i class="fa-solid fa-circle-info"></i><i class="fa-solid fa-xmark" onclick="hideNotification();" style="cursor:pointer; float:right;"></i>
            <strong>Success!</strong>
            <span class="text-success" style="white-space: pre-line"><br />@TempData["success"]</span>
        </div>
    </div>
}

@if (TempData["error"] != null)
{
    <div class="container" style="width: auto; float: right">
        <div class="alert alert-danger notification">
            <i class="fa-solid fa-triangle-exclamation"></i>
            <i class="fa-solid fa-xmark" onclick="hideNotification();" style="cursor:pointer; float:right"></i>
            <strong>Error!</strong>
            <span class="text-danger" style="white-space: pre-line"><br />@TempData["error"]</span>
        </div>
    </div>
}


<script>
   
</script>